# django-read-only-admin
# .travis.yml


language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - |
      pip install pipenv
      pip install -e .[test]
script:
  - make tox
after_success:
  - |
      make coverage
