# django-read-only-admin
# .github/workflows/check-requirements.yml


name: "check-requirements"
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  workflow_call:
env:
  DEFAULT_PYTHON_VERSION: "3.10"
jobs:
  check-requirements:
    name: "check-requirements"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git clone"
        id: "git-clone"
        uses: "actions/checkout@v2"
      - name: "Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}"
        id: "set-up-python"
        uses: "actions/setup-python@v3.1.0"
        with:
          python-version: "${{ env.DEFAULT_PYTHON_VERSION }}"
      - name: "Pip cache"
        id: "pip-cache"
        uses: "actions/cache@v2"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}"
          restore-keys: |
            "${{ runner.os }}-pip-"
      - name: "Install requirements"
        id: "install-requirements"
        run: "make install"
      - name: "Check outdated requirements"
        id: "check-outdated-requirements"
        continue-on-error: true
        run: "pip-outdated"
