# django-read-only-admin
# .github/workflows/test.yml


name: "test"
on:
  workflow_dispatch:
  workflow_call:
env:
  NAME: "xicon"
jobs:
  test:
    name: "${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: "Git clone"
        id: "git-clone"
        uses: "actions/checkout@v2"
      - name: "Set up Python ${{ matrix.python-version }}"
        id: "set-up-python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Pip cache"
        id: "pip-cache"
        uses: "actions/cache@v2"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.cfg') }}"
          restore-keys: |
            "${{ runner.os }}-pip-${{ matrix.python-version }}-"
            "${{ runner.os }}-pip-"
      - name: "Temporarily save coverage statistics"
        id: "temporarily-save-coverage-statistics"
        uses: "actions/cache@v2"
        with:
          path: ".coverage"
          key: ".coverage-${{ github.run_id }}-${{ github.run_number }}"
      - name: "Install requirements"
        id: "install-requirements"
        run: "make install"
      - name: "Run tests"
        id: "run-tests"
        env:
          PLATFORM: "${{ matrix.platform }}"
        run: "make tox"
